# -*- coding: utf-8 -*-
"""
Configuration file for the Sphinx documentation builder.

This file only contains a selection of the most common options. For a full
list see the documentation:
https://www.sphinx-doc.org/en/master/usage/configuration.html
"""

# -- Path setup --------------------------------------------------------------
#
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

from __future__ import annotations

import os
import sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('../src'))

import src.salespyforce.utils.version


# -- Project information -----------------------------------------------------

project = 'SalesPyForce'
copyright = '2026, Jeff Shurtliff'
author = 'Jeff Shurtliff'

# The short X.Y version
version = src.salespyforce.utils.version.get_major_minor_version()
# The full version, including alpha/beta/rc tags
release = src.salespyforce.utils.version.get_full_version()

# The documentation title used throughout this configuration file.
SALESPYFORCE_DOC_TITLE = 'SalesPyForce Documentation'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = '7.4.7'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.napoleon',
    'sphinx.ext.autosectionlabel',
    'myst_parser',
    'sphinx_favicon',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'desktop.ini', 'README.md']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'


# -- MyST configuration -----------------------------------------------------

# Enable syntax extensions
myst_enable_extensions = [
    'colon_fence',
    'deflist',
    'fieldlist',
    'replacements',
    'strikethrough',
]

# Open all external links in a new tab
myst_links_external_new_tab = True

# URI schemes that are converted to external links
myst_url_schemes = ['http', 'https']

# Heading level depth to assign HTML anchors
myst_heading_anchors = 3

# tasklist: Enable checkboxes
myst_enable_checkboxes = True


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'pydata_sphinx_theme'

# Add the favicon (unused because sphinx_favicon extension is being used)
# html_favicon = '_static/favicon.ico'

# Theme options are theme-specific and customize the look and feel of a theme.
html_theme_options = {
    'logo': {
        'text': 'SalesPyForce',
    },
    # 'github_url': 'https://github.com/jeffshurtliff/salespyforce',

    # Right side of the top navbar
    'navbar_end': ['theme-switcher', 'navbar-icon-links'],
    'icon_links': [
        {
            'name': 'GitHub',
            'url': 'https://github.com/jeffshurtliff/salespyforce',
            'icon': 'fa-brands fa-github',
        }
    ],

    # Reasonable code highlighting defaults
    'pygment_light_style': 'tango',
    'pygment_dark_style': 'monokai',
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add custom CSS (not necessary for only custom.css)
# html_style = '_static/custom.css'

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# Allow the autosection feature to allow document prefixes
autosectionlabel_prefix_document = True

# Suppress 'duplicate label' warnings from the autosection feature
suppress_warnings = [
    'autosectionlabel.changelog'
]


# -- Options for sphinx-favicon ----------------------------------------------

favicons = [
    {'rel': 'icon', 'sizes': '16x16', 'href': 'salespyforce-favicon-16x16.png'},
    {'rel': 'icon', 'sizes': '32x32', 'href': 'salespyforce-favicon-32x32.png'},
    {'rel': 'apple-touch-icon', 'sizes': '180x180', 'href': 'salespyforce-apple-touch-icon-180x180.png'},
]


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'salespyforce'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'salespyforce.tex', SALESPYFORCE_DOC_TITLE,
     'Jeff Shurtliff', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'salespyforce', SALESPYFORCE_DOC_TITLE,
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'salespyforce', SALESPYFORCE_DOC_TITLE,
     author, 'salespyforce', 'A Python toolset for performing Salesforce API calls',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'requests': ('https://requests.readthedocs.io/en/latest/', None),
}

# -- Options for tοdο extension ----------------------------------------------

# If true, `tοdο` and `tοdοList` produce output, else they produce nothing.
todo_include_todos = True
