name: Python package

on: [push]

jobs:
  build:
    name: ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'macos-latest']
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        macos-target: ['10.10']
        exclude:
          -   os: 'ubuntu-20.04'
              python-version: '3.10'
        include:
          - os: 'macos-11'
            python-version: '3.10'
            macos-target: '11.0'
          - os: 'macos-11'
            python-version: '3.9'
            macos-target: '11.0'
          - os: 'macos-11'
            python-version: '3.8'
            macos-target: '11.0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

#    - name: Test with pytest
#      run: |
#        pip install pytest
#        pytest
#
#    - name: Code coverage with codecov and pytest-cov
#      run: |
#        pip install codecov
#        pip install pytest-cov
#        pytest --cov-report=xml --cov=salespyforce src/salespyforce/utils/tests/ --color=yes
#        codecov -t e30bdae3-2111-4f8e-a603-ec8457f934a6

    - name: Python security check using Bandit
      if: ${{ (matrix.os != 'macos-latest') && (matrix.os != 'macos-11') }}
      uses: Joel-hanson/bandit-report-artifacts@V1
      with:
        ignore_failure: true


    - name: PyCharm Python Security Scanner
      if: ${{ (matrix.os != 'macos-latest') && (matrix.os != 'macos-11') }}
      uses: tonybaloney/pycharm-security@1.14.0
      with:
        ignore_failure: true
